version: '3.7'

services:
  servidor-php:
    image: fjortegan/dwes:php
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
    volumes:
      - ./codigo-php:/var/www/html/

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/      
    environment:
      MYSQL_DATABASE: tienda
      MYSQL_USER: encargado
      MYSQL_PASSWORD: diccionario
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
